version: '3.8'  

services:
  db:
    image: mysql:latest       
    container_name: mysql-db2  
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: musicdb
      MYSQL_USER: smrithika
      MYSQL_PASSWORD: musicpassword
    ports:
      - "3316:3306"           
    volumes:
      - db_data:/var/lib/mysql  


volumes:
  db_data:                   
